export const getPermissionsAsync = jest.fn()
export const requestPermissionsAsync = jest.fn()
export const getExpoPushTokenAsync = jest.fn()
export const setNotificationHandler = jest.fn()
export const addNotificationResponseReceivedListener = jest.fn().mockReturnValue({ remove: jest.fn() })
